name: Publish new version

on:
  push:
    tags:
      - 'v*.*.*'
    
jobs:
  generate-release-archive:
     name: Generate release archive
     runs-on: windows-latest
     
     permissions:
       contents: write
       issues: write

     steps:
       - name: Checkout
         uses: actions/checkout@v2
         with:
           fetch-depth: 0

       - name: Set up JDK
         uses: actions/setup-java@v2
         with:
           java-version: '15'
           distribution: 'adopt'
           cache: maven

       - name: Build with Maven
         run: mvn --batch-mode --update-snapshots verify
  
       - name: Create release
         uses: ncipollo/release-action@v1
         with:
           artifacts: "use-assembly/target/*.zip"
           generateReleaseNotes: true

       - name: Create "Bump Version" Issue
         uses: JasonEtco/create-an-issue@v2
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           OLD_USE_VERSION: ${{github.ref_name}}
         with:
           filename: .github/ISSUE_TEMPLATE/version_update.md
           